import type { Module } from 'langium';
import { inject } from 'langium';
import { BPMNmlValidator } from './bpmn-validator.js';
import { BPMNmlScopeProvider } from './bpmn-scope-provider.js';
import type { LangiumServices, PartialLangiumServices, LangiumSharedServices, DefaultSharedModuleContext } from 'langium/lsp';
import {
    createDefaultModule,
    createDefaultSharedModule
} from 'langium/lsp';
import { BPMNmlGeneratedModule, BPMNmlGeneratedSharedModule } from '../../generated/module.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BPMNmlAddedServices = {
    validation: {
        BPMNmlValidator: BPMNmlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BPMNmlServices = LangiumServices & BPMNmlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BPMNmlModule: Module<BPMNmlServices, PartialLangiumServices & BPMNmlAddedServices> = {
    validation: {
        BPMNmlValidator: (services) => new BPMNmlValidator(services)
    },
    references: {
        ScopeProvider: (services) => new BPMNmlScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBPMNmlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    BPMNml: BPMNmlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BPMNmlGeneratedSharedModule
    );
    const BPMNml = inject(
        createDefaultModule({ shared }),
        BPMNmlGeneratedModule,
        BPMNmlModule
    );
    shared.ServiceRegistry.register(BPMNml);
    return { shared, BPMNml };
}
